### ISSUE TITLE
Dont work for me

### ISSUE THREAD

**Issue by tamixx** [Pirater12/Mk7se#1]
Dont work on o3ds luma 11.2 eur

**Comment by tamixx** [comment]
Block at 
Success 1
Success 2
Succes 3
And it return to home with force reboot

**Comment by RyanAnayaMc** [comment]
Didn't put SystemX files in /mk7se/.

**Comment by hax0kartik** [comment]
@tammix Do you have SystemX files in a folder named mk7se ? https://github.com/Pirater12/Mk7se/blob/master/README.md

**Comment by tamixx** [comment]
I've found the problem it work after i update mk7 to version 1.1 and backup the save again
