### ISSUE TITLE
The editor doesn't actually edit saves.

### ISSUE THREAD

**Issue by HunterAhlquistEdu** [Pirater12/Mk7se#2]
I'm on new 3ds version 11.4 with boot9strap and the latest version of Mario Kart 7 (USA)
The application opens just fine, but despite it telling me that it has edited the save when I enter the game it does not show any change.

**Comment by hax0kartik** [comment]
There was a bug which I fixed just now. Please download v2.1 from the releases.Thanks for opening an issue and making me aware of that bug. 👍

**Comment by HunterAhlquistEdu** [comment]
it all works now thanks! I tried to unlock all the tracks, characters, etc but it wouldn't work. Although that's irrelevant now because it's fully functional (although i haven't tried the online cheats because i dont like to do online cheating)
