### ISSUE TITLE
cant launch 3dsx version

### ISSUE THREAD

**Issue by wertyef** [Pirater12/Mk7se#3]
i am running 2ds 11.3 b9s 1.2 luma 8.0 hbl 2.0. when i launch it from homebrew launcher it asks me to select my region, when i do that the message please wait while your files are being imported then crashes with the code C8804470|4000000030700|0

**Comment by hax0kartik** [comment]
Try using the cia version from v2.1.It should be fixed now. @wertyef

**Comment by hax0kartik** [comment]
Also, this error code means that you're selecting the wrong region.Try selecting other regions

**Comment by wertyef** [comment]
okay it opened this time and i selected unlock all tracks, characters, vehicles etc, i press start and it exits and i assume it saves? i go on to mk7 and its corrupted so how do i restore the backups?

**Comment by wertyef** [comment]
ok cool i used the new 3dsx version and it worked, though id still like to restore my original save and add on top of that

**Comment by hax0kartik** [comment]
@wertyef  Steps to restore:-

1. Open up FBI
2. Select SD
3. Scroll Down and open mk7se
4. Open backup 
5. There must be  *only two* SystemX.dat files where X is a number from 0-9
6. Click on current directory , an "directory action" dialog will show up. Select "Copy all contents" from there.
7. Go back to main menu of FBI and select Titles
8. Scroll down until you see "MARIO KART 7" and press the A button a "title action" dialog box will show  up
9. Select Browse Save Data
10. Select "current directory" by pressing the A button and select Paste
